#!/bin/sh

QMAILDIR=`head -1 conf-home`

# get user and group id's
GRPS=`ls -l $QMAILDIR/bin/qmail-send | awk '{ print $4; }'`
USRR=`ls -l $QMAILDIR/queue/lock/tcpto | awk '{ print $3; }'`

cp mkdkimkey qmail-sdkim qmail-vdkim   "$QMAILDIR/bin"
chown root."$GRPS" "$QMAILDIR/bin/mkdkimkey"
chown root."$GRPS" "$QMAILDIR/bin/qmail-sdkim"
chown root."$GRPS" "$QMAILDIR/bin/qmail-vdkim"

cp libqdkim  "$QMAILDIR/bin"
chown root."$GRPS" "$QMAILDIR/bin/libqdkim"
cp qdkimcrlf  "$QMAILDIR/bin"
chown root."$GRPS" "$QMAILDIR/bin/qdkimcrlf"
# config file - don't overwrite existing one
[ ! -f "$QMAILDIR/etc/qdkim.conf" ] && cp qdkim.conf "$QMAILDIR/etc"
chown root.$GRPS "$QMAILDIR/etc/qdkim.conf"
# manual pages
cp qmail-*.8       "$QMAILDIR/man/man8/"
cp qdkim.conf.5    "$QMAILDIR/man/man5/"
chown -R root.root "$QMAILDIR/man"

# tmp
mkdir -p "$QMAILDIR/tmp"
chown root.qmail "$QMAILDIR/tmp"
chmod 0770 "$QMAILDIR/tmp"
