.TH mkdkimkey 8 "" openqmail
.SH NAME
mkdkimkey \- create a key for domain and show DNS TXT records for bind
.SH SYNOPSIS
.B mkdomainkey [-h] [-p] [-s <selector>] domain
.SH DESCRIPTION
.B mkdomainkey
reads \fIdomain\fR from standard input and creates a public and private key for
\fIdomain\fR. The keys will be saved in \fIQMAILHOME/etc/dkimkeys/<domain>/\fR.
If keys for \fIdomain\fR are exists already, \fBmkdkimkey\fR prints a warning
and exits, leaving the keys alone. \fBmkdkimkey\fR needs sufficient access rights
to write the keys.

Before new keys can be created, the old ones have to be deleted. Afterwards a
new TXT record in DNS have to published.
.SH OPTIONS
.TP
.B -p
print the related DNS TXT record for the domain (\fBbind\fR format)
.TP
.B "-s <selector>"
define a selector instead of "default"
.TP
.B -h 
prints help and exits
.SH DEPENDENCIES
.B mkdkimkeys
requires a recent version (recommanded > 1.0.1f) of
.B openssl.
.SH "SEE ALSO"
qmail-sdkim(8)
