.TH qdkim.conf 5 "" openqmail
.SH NAME
qdkim.conf \- configuration file for qmail-sdkim and qmail-vdkim
.SH DESCRIPTION
\fIqdkim.conf\fR is the config file for \fBqmail-sdkim\fR and \fBqmail-vdkim\fR. Changes
will take effect immediatily. Lines beginning with a \fI#\fR will be ignored.
.P
\fIqdkim.conf\fR has 3 sections. Section 1 holds common option for \fBqmail-vdkim\fR AND
\fBqmail-vdkim\fR. Section 2 is needed by \fBqmail-sdkim\fR only. Respectively section 3
is required by \fBqmail-vdkim\fR only. See man pages \fIqmail-sdkim.8\fR and 
\fIqmail-vdkim.8\fR for their config options.
.P
Files have to be spezified with an absolute path always. The format is VAR=VALUE. To not
use a variable it is save to comment the related line out. Then \fBqmail-sdkim\fR and
\fBqmail-vdkim\fR are using build in defaults. Beware that \fIDISABLED\fR is default too.
.P
The common first section contains:
.TP 3
.IR DKLIB
Name of the external program which handles DKIM (default: \fBQMAILHOME/bin/libqdkim\fR)
.TP 3
.IR LOGGER
Name of the logger to use (default: \fBQMAILHOME/bin/splogger\fR)

.SH "AUTHOR"
Kai Peter (©2017), kp@openqmail.org
.SH "SEE ALSO"
qmail-sdkim(8),
qmail-vdkim(8)
