.TH qmail-sdkim 8 "" openqmail
.SH NAME
qmail-sdkim \- insert DKIM signatures to outgoing mails
.SH SYNOPSIS
.B qmail-sdkim 
.IR $@
.SH DESCRIPTION
.B qmail-sdkim
have to plugin into the 
.IR qmail-rspawn\->qmail-remote 
pipeline. There are several options to do this. One is to rename the original binary
.B qmail-remote
and make a symbolic link
.IR qmail-sdkim
\--> 
.IR qmail-remote.
Then 
.B qmail-sdkim
have to call the original (renamed) qmail-remote binary. A smarter option is to use 
.B qmail-bfrmt.
Beware that 
.B qmail-sdkim
manipulates the message, thus
.B qmail-sdkim 
calls (and have to do so)
.B qmail-remote
by itself.
.SH ENVIRONMENT VARIABLES
.B qmail-sdkim 
uses several variables, which can be set in the environment too.
.TP 3
.IR $XDKIM
This variable is set to
.B xdkim
by default. It have to contain the tool which does the real verification. An alternative is
.B libdkimtest.
.TP 3
.IR $DKSIGN
This have to contain the path to the private domainkeys file. If not defined the internal
variable 
.IR $DKDIR 
will be used, which by default starts with
.IR /etc/domainkeys/.
.TP 3
.IR $DKREMOTE
This have to contain the name of the real
.B qmail-remote
binary together with the full path if necessary. By default it is assumed that
.B qmail-sdkim 
and
.B qmail-remote
are in the same folder, so the most common value is usually
.IR $QMAILHOME/bin/qmail-remote.
.TP 3
.IR $NODKSIGN
If this variable exists, DKIM signing will be disabled.
.TP 3
.IR $SIGNINGLEVEL
This can contain a value from 1 to 3
.P
   1) sign the exact subdomain and if fails sign the parent domain
   2) sign the exact subdomain and if fails don't sign
   3) always sign the parent domain
   *) don't sign

   If
.IR $SIGNINGLEVEL 
is not set it defaults to 1.
.P
.TP 3
.IR $PARENTLVL
This can be used to define the level of the parent domain up to a maximum of 4. Default is 2, which means
the parent domain is a second level domain (e.g. "example.com"). In case it will be set to 3 then
the parent domain is a third level domain (.e.g. "example.co.uk"). This has only effect with singning level 3.
.SH DEPENDENCIES
.B qmail-sdkim
requires
.B xdkim
and uses default folder locations of it.
.SH "AUTHOR"
Kai Peter (©2014), kp@openqmail.org
.SH "SEE ALSO"
qmail-xdkim(8),
mkdomainkey(8),
qmail-vdkim(8)